### ISSUE TITLE
Some packages not being returned

### ISSUE THREAD

**Issue by huntc** [streambed/xdp-apps#6]
When querying for packages from the front end, the `dendrometer` and some other packages are not being picked up.

**Comment by huntc** [comment]
I partly resolved this via https://github.com/streambed/xdp-apps/commit/e9c7c280ceedd8571e4e8920f1b8802860f3ec4e. However, the front end when connected to the RPI at ICS isn't able to pull down updates.

Checking the logs, I see stuff like:

```
2019-05-28T08:18:28.769Z [08:18:28.767UTC] 127.0.0.1 com.cisco.streambed.cloudprovisioner WARN  RestartWithBackoffSource - Restarting graph due to failure. stack_trace: 
org.eclipse.jgit.api.errors.TransportException: Failure updating FETCH_HEAD: Too many open files in system
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:255)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:290)
	at com.cisco.streambed.cloudprovisioner.GitAppService$.$anonfun$run$6(GitAppService.scala:393)
	at akka.stream.impl.fusing.Scan$$anon$11.onPush(Ops.scala:415)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:480)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:574)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jgit.errors.TransportException: Failure updating FETCH_HEAD: Too many open files in system
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:238)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:124)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
	... 20 more
Caused by: java.io.IOException: Too many open files in system
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.eclipse.jgit.util.FS_POSIX.createNewFileAtomic(FS_POSIX.java:448)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:164)
	at org.eclipse.jgit.transport.FetchProcess.updateFETCH_HEAD(FetchProcess.java:339)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:236)
	... 23 more
```

I'm going to restart the service.

**Comment by huntc** [comment]
@longshorej Is there an issue here where we may not be closing files with jgit? I will also inspect the code. Restarting the service allowed the downloads to occur.
